### ISSUE TITLE
Duplicate IDs

### ISSUE THREAD

**Issue by drakemedic** [HospitalRun/hospitalrun-server#112] opened 2018-07-09 21:07 UTC
This is an odd one, and I don't know if it can be replicated.
I have 3 different patients with the same ID - P00001. They were the first 3 patients created on the system and I didn't notice it happening at the time. Subsequent patients have incremented IDs. Presumably the system should not be able to do this?

I don't know how to replicate this one as all newly-added patients have unique IDs.

**Comment by drakemedic** [comment] 2018-07-09 21:58
I don't really remember, but it was probably a combination of different
browser, same pc and possibly another - but not at the same time!

I know that's not very helpful, but I just noticed it tonight and thought
it was strange.

**Comment by MatthewDorner** [comment] 2018-07-18 05:59
it's happening if I use Firefox, but not Chrome. To reproduce:

- start with a database having >0 patients in it
- close HospitalRun tab and erase Firefox browser cache
- log in to HospitalRun, view list of patients. It will (incorrectly) show 0 patients. waiting for the database to sync doesn't seem to make any difference.
- add a patient. it will get P00001 even if that ID is already in use
- you will now also be able to see all the patients

same thing happens with inventory items. good thing you noticed, I will try to figure it out.

**Comment by MatthewDorner** [comment] 2018-07-24 20:36
OK, this behavior occurs if you refuse Push notifications. That's the pop-up that says something like "This website wants to send you notifications. Allow / Deny". And this is because the Push API is used to sync the database. Maybe it should be made more obvious that users need to Allow, since I and others Deny these requests out of habit.

**Comment by drakemedic** [comment] 2018-07-25 09:32
Indeed, I think it would need to be made explicit as many people refuse pop-ups routinely.
When I have installed hospitalrun, I usually accept the data storage request, but I don't think the push notification request shows every time if you have previously declined it.

**Comment by donaldwasserman** [comment] 2018-08-21 03:56
I'm going to close this issue and move it over to the front-end

**Closed by donaldwasserman** 2018-08-21 03:56 UTC
